title: All About Cayla perez
author: Cayla Perez
email: cperez2@ebnet.com
description: > # this means to ignore newlines until "baseurl:"
  Hi there :) Here you're going to learn all about this 17 year old girl!

# social links
twitter_username: Cayla610000576 # DO NOT include the @ character, or else the build will fail!
github_username:  cp3rez # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
